### ISSUE TITLE
Changing forum link

### ISSUE THREAD

**Issue by Dimtar** [stoopkid1/ezleague#115]
There used to be a way to change the forum link but this seems to have been deprecated. There needs to be a way to customize that link especially since it currently goes no where.

**Comment by bigbambu** [comment]
Hello!
Any news about this, I just re-installed the ezLeague but still the forum.php os missing the Forum link puts to no where # 
Thank You

**Comment by stoopkid1** [comment]
@Dimtar @bigbambu 
the ability to change the Forum URL in the navigation has been implemented https://github.com/stoopkid1/ezleague/pull/136

upgrade your installation to implement the new feature
