### ISSUE TITLE
Forgot Password?

### ISSUE THREAD

**Issue by Linusscout** [stoopkid1/ezleague#128]
Hello,

the link to the "Forgot Password?" site is broken ... the page rout me to http://www.mdloring.com/ezleague/forget.php

**Comment by stoopkid1** [comment]
@Linusscout i'll get this feature added asap

**Comment by stoopkid1** [comment]
@Linusscout the forgot password feature has been implemented into ezLeague version 3.4.6 https://github.com/stoopkid1/ezleague/pull/143
