### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by welaughindoors** [stoopkid1/ezleague#130]
I have setup, and installed ezleague, the install appeared successful, everything seemed to be working fine on my end until I attempted to register a normal account. It seems to be unresponsive, filling in the required fields and pressing submit does absolutely nothing.

Any suggestions or ideas on how to fix this issue? I feel like this is somehow related to the database, but do not have enough knowledge to really figure it out.

Thanks

**Comment by stoopkid1** [comment]
@welaughindoors could you please link me to your site? it's possible there is a database issue, but it could also be a jQuery / JavaScript error

**Comment by welaughindoors** [comment]
sure, http://bsgl.us/league/

**Comment by stoopkid1** [comment]
@welaughindoors a 500 Internal Server Error is being returned from the `submit.php` file when trying to register. would you be able to post your PHP error log? there should be mention of the error in the log file

**Comment by welaughindoors** [comment]
Certainly:

[Sun Jan 11 06:39:49.238126 2015] [mpm_prefork:notice] [pid 16830] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.5 configured -- resuming normal operations
[Sun Jan 11 06:39:49.238151 2015] [core:notice] [pid 16830] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jan 11 08:01:34.146150 2015] [:error] [pid 7878] [client 108.162.245.163:18484] script '/var/www/html/challenge.php' not found or unable to stat
[Sun Jan 11 09:01:35.885164 2015] [:error] [pid 7877] [client 108.162.245.38:42507] script '/var/www/html/profile.php' not found or unable to stat
[Tue Jan 13 20:20:30.248140 2015] [:error] [pid 7880] [client 141.101.105.176:43473] script '/var/www/html/wp-login.php' not found or unable to stat
[Tue Jan 13 20:20:30.848016 2015] [:error] [pid 7880] [client 141.101.105.176:43473] script '/var/www/html/admin.php' not found or unable to stat
[Wed Jan 14 03:37:09.239767 2015] [:error] [pid 14905] [client 108.162.216.157:9836] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:01.747699 2015] [:error] [pid 31640] [client 108.162.216.180:33981] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:33.618599 2015] [:error] [pid 14905] [client 108.162.216.180:35609] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:46.167043 2015] [:error] [pid 8094] [client 108.162.216.180:16140] PHP Notice:  Undefined offset: 0 in /var/www/html/league/lib/objects/class-user.php on line 11, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:46.167069 2015] [:error] [pid 8094] [client 108.162.216.180:16140] PHP Notice:  Undefined offset: 0 in /var/www/html/league/lib/objects/class-user.php on line 12, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:46.167072 2015] [:error] [pid 8094] [client 108.162.216.180:16140] PHP Notice:  Undefined offset: 0 in /var/www/html/league/lib/objects/class-user.php on line 13, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:46.167074 2015] [:error] [pid 8094] [client 108.162.216.180:16140] PHP Notice:  Undefined offset: 0 in /var/www/html/league/lib/objects/class-user.php on line 14, referer: http://bsgl.us/league/
[Wed Jan 14 03:41:46.167076 2015] [:error] [pid 8094] [client 108.162.216.180:16140] PHP Notice:  Undefined offset: 0 in /var/www/html/league/lib/objects/class-user.php on line 15, referer: http://bsgl.us/league/
[Wed Jan 14 03:47:13.572486 2015] [:error] [pid 31631] [client 108.162.216.180:50756] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 59, referer: http://bsgl.us/league/about.php
[Wed Jan 14 03:47:13.572507 2015] [:error] [pid 31631] [client 108.162.216.180:50756] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 60, referer: http://bsgl.us/league/about.php
[Wed Jan 14 03:47:13.572510 2015] [:error] [pid 31631] [client 108.162.216.180:50756] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 62, referer: http://bsgl.us/league/about.php
[Wed Jan 14 03:47:13.572512 2015] [:error] [pid 31631] [client 108.162.216.180:50756] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 63, referer: http://bsgl.us/league/about.php
[Wed Jan 14 03:47:29.938913 2015] [:error] [pid 31632] [client 108.162.216.180:60024] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/members.php
[Wed Jan 14 03:48:33.846157 2015] [:error] [pid 31637] [client 108.162.216.180:42149] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 59, referer: http://bsgl.us/league/members.php
[Wed Jan 14 03:48:33.846181 2015] [:error] [pid 31637] [client 108.162.216.180:42149] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 60, referer: http://bsgl.us/league/members.php
[Wed Jan 14 03:48:33.846196 2015] [:error] [pid 31637] [client 108.162.216.180:42149] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 62, referer: http://bsgl.us/league/members.php
[Wed Jan 14 03:48:33.846199 2015] [:error] [pid 31637] [client 108.162.216.180:42149] PHP Notice:  Undefined variable: reverse in /var/www/html/league/tpls/members/member-list.php on line 63, referer: http://bsgl.us/league/members.php
[Wed Jan 14 03:48:53.330806 2015] [:error] [pid 31640] [client 108.162.216.180:57311] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/members.php
[Wed Jan 14 03:48:59.265234 2015] [:error] [pid 14905] [client 108.162.216.180:31587] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/members.php
[Wed Jan 14 09:20:37.156467 2015] [:error] [pid 7878] [client 141.101.105.176:48480] script '/var/www/html/admin.php' not found or unable to stat
[Wed Jan 14 09:21:08.380531 2015] [:error] [pid 5487] [client 141.101.105.176:51663] script '/var/www/html/admin.php' not found or unable to stat
[Wed Jan 14 11:05:19.798681 2015] [:error] [pid 5492] [client 141.101.92.153:54773] script '/var/www/html/yandex.php' not found or unable to stat
[Wed Jan 14 17:14:27.006358 2015] [:error] [pid 5508] [client 141.101.92.41:25015] script '/var/www/html/wp-login.php' not found or unable to stat
[Wed Jan 14 17:14:27.701415 2015] [:error] [pid 5498] [client 141.101.92.41:35564] script '/var/www/html/admin.php' not found or unable to stat
[Wed Jan 14 18:28:32.703239 2015] [:error] [pid 7878] [client 141.101.105.176:23855] script '/var/www/html/wp-login.php' not found or unable to stat
[Wed Jan 14 18:29:23.878563 2015] [:error] [pid 5490] [client 141.101.105.176:55147] script '/var/www/html/admin.php' not found or unable to stat
[Thu Jan 15 13:20:32.561254 2015] [:error] [pid 5493] [client 108.162.254.213:28617] script '/var/www/html/admin.php' not found or unable to stat
[Thu Jan 15 13:20:50.583209 2015] [:error] [pid 5491] [client 108.162.254.213:41339] script '/var/www/html/admin.php' not found or unable to stat
[Thu Jan 15 21:36:24.690584 2015] [:error] [pid 20207] [client 108.162.216.157:11740] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:36:27.347960 2015] [:error] [pid 5494] [client 108.162.216.157:58658] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:36:27.616358 2015] [:error] [pid 5492] [client 108.162.216.157:59959] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:36:27.806565 2015] [:error] [pid 5493] [client 108.162.216.157:56561] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:36:27.977106 2015] [:error] [pid 5498] [client 108.162.216.157:45096] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:36:47.261064 2015] [:error] [pid 20186] [client 108.162.216.157:47943] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:36:48.817992 2015] [:error] [pid 20187] [client 108.162.216.157:50068] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:06.081018 2015] [:error] [pid 5498] [client 108.162.216.157:27731] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:11.606796 2015] [:error] [pid 20186] [client 108.162.216.157:25570] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:12.219872 2015] [:error] [pid 20187] [client 108.162.216.157:20555] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:12.382866 2015] [:error] [pid 20228] [client 108.162.216.157:61057] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:12.539408 2015] [:error] [pid 20197] [client 108.162.216.157:61527] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:12.712383 2015] [:error] [pid 20195] [client 108.162.216.157:25901] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:12.853500 2015] [:error] [pid 20196] [client 108.162.216.157:19223] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:13.035144 2015] [:error] [pid 20207] [client 108.162.216.157:47677] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:14.291201 2015] [:error] [pid 5494] [client 108.162.216.157:62391] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:14.549273 2015] [:error] [pid 5492] [client 108.162.216.157:39288] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:14.707485 2015] [:error] [pid 5498] [client 108.162.216.157:31987] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:14.910982 2015] [:error] [pid 20186] [client 108.162.216.157:29931] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:15.103155 2015] [:error] [pid 20187] [client 108.162.216.157:44434] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:15.275376 2015] [:error] [pid 20228] [client 108.162.216.157:32863] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:15.397318 2015] [:error] [pid 20197] [client 108.162.216.157:25577] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/
[Thu Jan 15 21:37:15.899521 2015] [:error] [pid 20195] [client 108.162.216.157:50124] PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/league/lib/objects/class-user.php on line 39, referer: http://bsgl.us/league/

**Comment by stoopkid1** [comment]
@welaughindoors perfect, thanks for the error log. the issue is the `mcrypt` library/extension is not installed. this should help you here to enable it: http://stackoverflow.com/questions/12479983/cant-find-mcrypt-call-to-undefined-function-laravel-mcrypt-create-iv

very simple to do. once you've updated your `php.ini` file, restart your web server and you'll be all set. if you are unable to restart it or modify `php.ini`, simply contact your web host provider and let them know you need this library/extension enabled.

if they have an issue, this library is used to encrypt the salt / hash strings, which are used for the user login as an extra security measure. they should not have a problem with this.
