### ISSUE TITLE
Friends can see the mail addy

### ISSUE THREAD

**Issue by Linusscout** [stoopkid1/ezleague#131]
Hello 

User can see the email address of friends. We Should be able to configure this security setting.

**Comment by stoopkid1** [comment]
@Linusscout i'll add that as a setting. originally, the email addy was hidden even for friends, but there was a request to have it shown.

**Comment by stoopkid1** [comment]
@Linusscout i'll have this setting implemented within the next few days.

**Comment by stoopkid1** [comment]
@Linusscout your feature request has been implemented https://github.com/stoopkid1/ezleague/pull/142
