### ISSUE TITLE
Registration remains open past registration date

### ISSUE THREAD

**Issue by Schamus** [stoopkid1/ezleague#132]
Teams are still able to register for leagues after the listed registration end date.

**Comment by stoopkid1** [comment]
@Schamus i'll be release a fix for this by Sunday. thanks for pointing this out

**Comment by stoopkid1** [comment]
@Schamus this bug has been fixed and released in the new 3.4.4 version of ezLeague. thanks for reporting it - https://github.com/stoopkid1/ezleague/pull/141
