### ISSUE TITLE
mysql database

### ISSUE THREAD

**Issue by agreements** [stoopkid1/ezleague#133]
Possible to get the mysql database dumb? Would be helpful since my browser doesn't do anything except writing error msg. 

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /home/www/myweb/lib/class-db.php on line 46
No news items to display
etc etc.

**Comment by stoopkid1** [comment]
@agreements i don't have any demo data to provide.once you create a news post, that error will go away.

**Comment by stoopkid1** [comment]
@agreements 
dummy data is now available in the latest ezLeague update (version 3.4.3) https://github.com/stoopkid1/ezleague/pull/140
