### ISSUE TITLE
view user in comments

### ISSUE THREAD

**Issue by zigstum** [stoopkid1/ezleague#135]
Bad address on view user link on a comment.
/tpls/news/news-comments.php, line 15:
---
`<a href="view-user.php?id=<?php echo $comment['author_id']; ?>">`
change to...
`<a href="view-member.php?id=<?php echo $comment['author_id']; ?>">`

**Comment by stoopkid1** [comment]
@zigstum 
thanks for reporting this bug. i'll release an update with the corrected code.

**Comment by stoopkid1** [comment]
@zigstum 
code update has been pushed https://github.com/stoopkid1/ezleague/pull/137
