### ISSUE TITLE
Tournament Feature

### ISSUE THREAD

**Issue by stoopkid1** [stoopkid1/ezleague#145]
Build Tournament feature into ezLeague

**Comment by Shebastian** [comment]
types:
free registration
tickets
admin invites

(Tickets would put into the league - 1st Gold ticket 1-3 silver ticket (position on seasson)

**Comment by stoopkid1** [comment]
@Shebastian thanks for the suggestions, please keep them coming. i don't really follow/understand the "tickets" type, could you explain it a bit further? i like the idea of public/private tournaments (similar to admin invites), so i'll try to implement that.

all tournaments/leagues will be "free registration" -- i won't be implementing any sort of payment functionality in the free version of ezLeague (that's much more of a licensed feature).

**Comment by hraki** [comment]
I don't know if it's possible or not, but when its a tournament 1vs1, instead of the players need to create a team to join (like the league mode), why not being able to join as a member instead of needed to create a team

**Comment by stoopkid1** [comment]
@hraki i'll look into developing a feature like this. you're not the first person to suggest it -- so i know it's something that could be useful. when a user creates a team, they're automatically made the team admin, so a user could create a team and use their username as the team name.

there is really only 1 issue with 1v1 tournaments:
if a user is already in a team (lets say, for a Counter-Strike league), if there is a 1v1 tournament that user would want to join, they would have to leave their current team, then create their own team so they could join the 1v1 tournament...hope that makes sense.

**Comment by stoopkid1** [comment]
tournament feature now implemented https://github.com/stoopkid1/ezleague/pull/155
