### ISSUE TITLE
mysqli_fetch_assoc() error

### ISSUE THREAD

**Issue by Dmitchell94** [stoopkid1/ezleague#150]
I run my own webserver and I have gotten ezleague installed but now it repeatedly displays:

Warning: mysqli_fetch_assoc() expects parameter 1 to be mysqli_result, boolean given in /home/forgewareinc/public_html/ogl/lib/class-db.php on line 46

How do i fix this?

**Comment by zigstum** [comment]
https://github.com/stoopkid1/ezleague/issues/133
A previous post:

@agreements <https://github.com/agreements> ...once you create a news post,
that error will go away.

**Comment by Dmitchell94** [comment]
It wont let me log in either though tells me invalid login when i use admin ezadmin
