### ISSUE TITLE
constant redirect

### ISSUE THREAD

**Issue by Dmitchell94** [stoopkid1/ezleague#151]
just ran the installer this morning was about to delete the install.php file and now it wont stop trying to redirect me to the install file

**Comment by Shebastian** [comment]
'/lib/db.class.php' A N D
'/admin/lib/db.class.php' and modify your site URL and database values

**Comment by Dmitchell94** [comment]
i already did that

**Comment by Dmitchell94** [comment]
any ideas whats causing the constant redirects

**Comment by zigstum** [comment]
Not without looking at your setup.
Stuff like this is usually a simple mistake on config, or cookies not setting, or folders with bad permission.
You can follow the chain using firefox inspector and watch the header requests and responses in the net tab. You can mail me ezl[at]zigstum.com if you want some help. Don't send any passwords through the mail list.

**Comment by stoopkid1** [comment]
If you have properly installed ezleague, check to make sure the database /
tables have been created.

If they have been, then the install.php file should have been deleted. If
your MySQL config is correct, and the database/tables have been created, go
ahead and delete the install.php file.

On Fri, Apr 17, 2015 at 4:24 AM, zigstum <notifications@github.com> wrote:

> Not without looking at your setup.
> Stuff like this is usually a simple mistake on config, or cookies not
> setting, or folders with bad permission.
> You can follow the chain using firefox inspector and watch the header
> requests and responses in the net tab. You can mail me ezl[at]zigstum.com
> if you want some help. Don't send any passwords through the mail list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stoopkid1/ezleague/issues/151#issuecomment-93951181>.
>



-- 
Michael Loring
Lead Web Applications Engineer
The Chicago Sun-Times Media Company

President
Loring Enterprises

cell:         773 870 5442
http://www.mdloring.com

**Comment by hraki** [comment]
I tried a new installation and I have the same problem, is always redirecting to /admin/install.php

the tables are all created in DB, and if I delete the install.php it says the file don't existe (like it suppose to say) and don't let me see the /index.php only the admin painel

**Comment by hraki** [comment]
Check the /lib/class-db.php and /admin/lib/class-db.php probably you have the  "var $prefix	  =ezl" with the prefix different on one
