### ISSUE TITLE
Install Issue 

### ISSUE THREAD

**Issue by andyhay123** [stoopkid1/ezleague#160]
Ive uploaded all the files to my web host then filled out the boxes on the install but when i click install it just refreshes the page and nothing happens

**Comment by stoopkid1** [comment]
@andyhay123 
did you edit the `/lib/class-db.php` and `/admin/lib/class-db.php` files? you need to input your database information there.

**Comment by andyhay123** [comment]
Yeah i have done that then loaded the site up and it took me to the page to
fill out the ezleague installation form but when i fill it in and click run
installation it just reloads the page then nothing happens it creates all
the fields though in my sql

**Comment by stoopkid1** [comment]
@andyhay123 
please link me to your site

**Comment by stoopkid1** [comment]
@andyhay123 if you have Skype, my screenname is "RedCrestLoring"

**Comment by stoopkid1** [comment]
@andyhay123 what web host are you using? i just saw the error you sent me
`(Warning: mysqli::mysqli(): (42000/1203): User modernm6_andy already has more than 'max_user_connections' active connections in /home/modernm6/public_html/lib/class-db.php on line 26)` -- are you still receiving this error? this is the first of it's kind that has been reported

**Comment by andyhay123** [comment]
yeah im still getting that error im using x10hosting my website is
http://modernmafia.x10.mx/index.php

**Comment by stoopkid1** [comment]
@andyhay123 there are a few updates i'm going to make in light of the error you're getting, but you need to contact your web hosting (reference: https://x10hosting.com/community/threads/new-error-max_user_connections-for-mysql.196025/) 
it sounds like your web host temporarily disabled your accounts database access due to the amount of queries that are run when ezLeague installs.

**Comment by andyhay123** [comment]
Oh okay thanks for your help

**Comment by stoopkid1** [comment]
an important update has been released regarding the `max_user_connections` issue that is mentioned above
https://github.com/stoopkid1/ezleague/pull/162

**Comment by roberto722** [comment]
The installation issue isn't still solved because i still that error...
