### ISSUE TITLE
League issue 

### ISSUE THREAD

**Issue by andyhay123** [stoopkid1/ezleague#163]
Hi ive been trying to set up leagues through the admin panel but when i fill out the form it creates one but doesnt show up in the admin section named current league and it shows up on the site with dates 1970 i have changed my timezone so i dont know why its doing it

**Comment by stoopkid1** [comment]
Create a League, then Create a Season for that League. Once you've created
a Season, you can modify the Season Dates.

On Tue, Apr 28, 2015 at 6:08 PM, andyhay123 <notifications@github.com>
wrote:

> Hi ive been trying to set up leagues through the admin panel but when i
> fill out the form it creates one but doesnt show up in the admin section
> named current league and it shows up on the site with dates 1970 i have
> changed my timezone so i dont know why its doing it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stoopkid1/ezleague/issues/163>.
>



-- 
Michael Loring
Lead Web Applications Engineer
The Chicago Sun-Times Media Company

President
Loring Enterprises

cell:         773 870 5442
http://www.mdloring.com

**Comment by andyhay123** [comment]
i dont have the option to create a season on my admin panel

**Comment by andyhay123** [comment]
Can you help me when i create a league in the admin panel it just refreshes but does not add anything

**Comment by msdeliquent** [comment]
check phpmyadmin if script created any tables
