### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by labyad** [stoopkid1/ezleague#165]
First of all congratulations the script is amazing!

I just want to say some ideas to make the script even better.

The first is for 1on1 leagues or tournaments the players can join with their username instead of create a team.

The second one is the possibility of the players can join more teams ( at least 2) because he can have a team to play a 5v5 tournament, but if the player wants to play a 2v2 tournament with a friend they have to leave their main team.

The third is a award system, when you create a tournament you can choose the prize for the 1st,2nd and 3rd place and will show on the View-Tournament and appear on the player profile he won the tournament (like a log system)

and the last is a Ladder mode (with ELO rating) league mode is great, but the ELO rating is better for competition.

I don't know but you can make modules and sell it. have the base script and then have that modules(with a license) the players can buy 

Thanks and keep the good work!

**Comment by stoopkid1** [comment]
@labyad very happy to hear you're enjoying the script, and thank you for the suggestions. those are the type of features that i will be building into the licensed version of ezLeague, which has no release date set yet. right now i'm unsure if i'll be splitting the increased/new functionality into modules that can be purchased individually, or if everything will be bundled together.

regarding the ELO system, both ezLeague v1 & v2 were based on an ELO Ladder Challenge system, but they did not include the league/tournament system.

**Comment by labyad** [comment]
Thanks for the answer! Can't wait to see the new features!

oh and there is any chance to have the ELO Ladder challenge system on this last version? adding the ELO code of the v1 & v2 and the DB tables?
