### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by Warrior70uw** [stoopkid1/ezleague#167]
Firstly, i would like to thank you on a brilliant system.

I have had a play with it and love it sofar. The question i have, is are you planning on making a forum system that is compatible with this database so users would only have to register and signup once to both your system and the forum system?

**Comment by stoopkid1** [comment]
@Warrior70uw glad you're enjoying the script. yes, i actually have written a forum system that is built into ezLeague, but there were multiple requests to simply have it link to their 3rd party forum. i'll look into re-implementing the forum code in a future release.

the original forum included:
- topics
- replies
- post count
- user signatures
- public forums
- private forums (each team/guild had their own private forum created when the team was created)

**Comment by Warrior70uw** [comment]
This sounds exactly what i am after. I am looking at launching a new venture and this script with forums would be exactly what i am looking for.
Once the forums side of it has been released, i can then push this idea out and it will then really publisize your work on the script. I cant wait. Many thanks for getting back to me.
