### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by msdeliquent** [stoopkid1/ezleague#170]
when i wanted to install the script, the following lines appeared to me on screen:

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/sites/p/ps/pss/pssarena.za.pl/header.php on line 33 Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home/sites/p/ps/pss/pssarena.za.pl/header.php on line 33 Parse error: syntax error, unexpected T_STRING in /home/sites/p/ps/pss/pssarena.za.pl/header.php on line 33

can you help me?

**Comment by stoopkid1** [comment]
@msdeliquent line 33 in `header.php` references the Codebird library that is used to display Twitter Tweets in the right sidebar. The library uses a method called "namespaces", which is only supported in PHP 5.3+. Check with your web host and see what PHP version they are running. 

Assuming your web host has PHP 5.2 or below installed, remove your Twitter Handle from the Admin Panel > Site Settings > Twitter, and the error should go away.

**Comment by msdeliquent** [comment]
ok problem solved, i moved to another hosting.
