### ISSUE TITLE
Start new tournament

### ISSUE THREAD

**Issue by roofzera** [stoopkid1/ezleague#173]
Unable to start new tournament. I fill in all the data, and does not insert the DB. Is there any solution?

**Comment by stoopkid1** [comment]
Tournaments cannot have matches generated until it has reached the max limit of teams signups.

Are you having trouble creating a new tournament? (creating via 'starting' are different)

**Comment by roofzera** [comment]
@stoopkid1 Man, thank you for responding. I need much of your script to work in a Brazilian league.

When I click to create a new tournament, complete all fields with the required data, but adds nothing to the database, and not in the tournament list. And I can not put alloy subscription / open tournament. How to do?

**Comment by msdeliquent** [comment]
same issue here, not only a tournament isimpossible to create but even a league and users cannot be registered :(

**Comment by msdeliquent** [comment]
i don't know why, but the instalation script doesn't create tables in my database and i provide a good values in db.class files.

**Comment by msdeliquent** [comment]
ok, my problem solved - f**k free hosts...

**Comment by stoopkid1** [comment]
@msdeliquent glad this was resolved. yes, some free hosts have created numerous issues. it's tough to know all of their individual setups, so sorry you had problems getting started.
