### ISSUE TITLE
Login frmo the main website sending me to HTTP 404?

### ISSUE THREAD

**Issue by calibershock** [stoopkid1/ezleague#175]
Hello,

I'm trying out ur script from the download MASTER zip file for the 3.5.7

I've installed it on asite.

When I click the top right Login Tab next to Register, I enter in some details and click LOGIN button but it then redirects me to a HTTP 404 page? It's not allowing me to log in? 

It takes me to mysite.com/index.html  ?? 
index.html? is that correct?

Thanks

**Comment by stoopkid1** [comment]
@calibershock be sure to check your `lib/class-db.php` and `admin/lib/class-db.php` files to make sure the `$site_url` variable is set. you can also login to your Admin Panel > Site Settings > URL and make sure the URL is properly set.

i just did a fresh installation and did not experience the same problem.
