### ISSUE TITLE
Can't Generate Matches in Leagues, even with Season added and within date

### ISSUE THREAD

**Issue by calibershock** [stoopkid1/ezleague#179]
See Screen shot: 
Can't Generate Matches in Leagues, even with Season added and within date.
As you can see, when I go to click dropdown box, it's empty, I can't generate any Matches.

![img_2074](https://cloud.githubusercontent.com/assets/13165611/8509706/90582f74-22ab-11e5-88b9-2686760054c6.JPG)
![img_2073](https://cloud.githubusercontent.com/assets/13165611/8509707/905d73a8-22ab-11e5-8b35-8174691cf3ee.JPG)

**Comment by stoopkid1** [comment]
@calibershock try creating a new league without "unlimited" for the number of games (weeks) and max teams. i think this bug is specifically for "unlimited" games, which is a selection i need to remove (it's not possible to generate matches when the number of matches is unlimited).

**Comment by calibershock** [comment]
Perfect, worked

**Comment by stoopkid1** [comment]
@calibershock awesome, glad to hear it. i'm currently building a "Get Started" guide that should alleviate issues like this for new users. thank you for being patient.
