### ISSUE TITLE
Install Issue 

### ISSUE THREAD

**Issue by roberto722** [stoopkid1/ezleague#189]
Hi,
installing the latest relase i meet this problem because the install when i click on the button to install just refresh the page, and when i delete the install file i get this error in my homepage
![untitled](https://cloud.githubusercontent.com/assets/12681493/9154826/4d75ec38-3ea2-11e5-8edc-aa5a91fb5926.png)

I've already checked my database user,pass,and host so i cant understand where is the problem

**Comment by wadie100** [comment]
I get the exact same thing. 
max_user_connections error-> are the connections of the script managed properly?

**Comment by stoopkid1** [comment]
@wadie100 @roberto722 if you're on a shared hosting platform, you need to contact them and ask about multiple mysql queries being fired.

the installer performs multiple table creations & insertions.

**Comment by wadie100** [comment]
Hi Michael,

Their answer was that I needed to check the code and 'reconnect' often enough... The code is too complex for me to know whether connections are maintained properly, or not. Their max user connections is set to 3 according to the error message

Kind regards

**Comment by stoopkid1** [comment]
@wadie100 can you link me to your site/installation? if you have phpMyAdmin, we can get you setup by importing the database. also, what shared hosting company are you using? i'll look into modifying the installation script, but i won't be able to do it immediately.

**Comment by wadie100** [comment]
Hi Michael,

the link to the installation is bedotal.esy.es

My site is hosted by hostinger.nl
I do have phpmyadmin. Is there a dump of the tables somewhere that I can
use to import?

Kind regards

**Comment by stoopkid1** [comment]
@wadie100 yes, please send me an email: MDLoring[at]gmail.com and i'll get you the database structure

**Comment by roberto722** [comment]
Hi im using the same hoster, can u pls help me too ?

**Comment by stoopkid1** [comment]
@roberto722 send me an email and i'll provide you with the same SQL dump that i just passed along to wadie. you will need phpMyAdmin access to do this.

**Comment by roberto722** [comment]
Ok. Sure, i have acces to phpMyAdmin

**Comment by stoopkid1** [comment]
closing as this issue cannot be resolved due to the specific shared hosting mysql configuration that deals with limited mysql connections
